# Generated by Django 6.0.2 on 2026-02-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
