# Generated by Django 6.0.2 on 2026-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0002_alter_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='softwares/'),
        ),
    ]
