# Generated by Django 6.0.2 on 2026-02-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0003_software_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mansagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('RESPONDIDO', 'Respondido')], default='NOVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='softwares.software')),
            ],
        ),
    ]
