# Generated by Django 6.0.2 on 2026-02-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0004_interesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interesse',
            old_name='mansagem',
            new_name='mensagem',
        ),
    ]
