# Generated by Django 6.0.2 on 2026-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0005_rename_mansagem_interesse_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
