# Generated by Django 6.0.2 on 2026-02-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
