# Generated by Django 6.0.2 on 2026-02-13 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0010_remove_interesse_email_remove_interesse_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='softwares.interesse')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
